### ISSUE TITLE
where are the classes .css?

### ISSUE THREAD

**Issue by slo74design** [upplex/upBootstrap3WP#1]
Hi,
thanks for your fantastic framework!
I tried to custom css but many classes missing in css file upbootwp.css.

For instance, if i try to modify the body_class, it's impossible because this class on upbootwp.css doesn't exist. Where are the classes?

Thanks,
Best Regards
Slo74

**Comment by AS-OLD** [comment]
Hi,

which classes in specific do you mean ? 

In case of you can always edit everything in the less files and compile your own css file with http://crunchapp.net/ 

I would also recommend to edit the less file and then compile it. You can use regular css expressions overall and is pretty easy. Of course I will fix it when you tell me the specific classes.
