### ISSUE TITLE
Strict Standards Notices

### ISSUE THREAD

**Issue by daslicht** [upplex/upBootstrap3WP#5]
I get :
Strict Standards: Declaration of Upbootwp_Walker_Nav_Menu::start_lvl() should be compatible with Walker_Nav_Menu::start_lvl(&$output, $depth = 0, $args = Array) in /Users/daslicht/Sites/Shigge-Shanga/wp-content/themes/upBootstrap3WP/inc/general/class-Upbootwp_Walker_Nav_Menu.php on line 152

**Comment by AS-OLD** [comment]
set WP_DEBUG to false in wp-config.php

**Comment by daslicht** [comment]
thats bad practice , especially if you like to develop things besides you theme ...

**Comment by AS-OLD** [comment]
as far as I know that is a custom bug with the walker menu

**Comment by bonzysalesman** [comment]
I also experienced this. Turns out setting WP_DEBUG to false in wp-config.php does work. However, here's a trick: turn WP_DEBUG to true to see all errors, fix all of them and when the Strict Standards notice/error is all you're getting then set WP_DEBUG back to false.
